{
 "title": "Homelab",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(up,job)" } },
   {
    "name": "host",
    "query": {
     "query": "label_values(system_cpu_time{job=\"$job\"},host_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Speed Test",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(speedtest_download_speed_Bps{user_isp=\"AT&T U-verse\"})",
     "legendFormat": "Download"
    },
    {
     "expr": "avg(speedtest_upload_speed_Bps{user_isp=\"AT&T U-verse\"})",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "% ads blocked",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pihole_ads_percentage_today{hostname=\"192.168.2.110\"}"
    }
   ]
  },
  { "title": "Host Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "$host CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 8 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(system_cpu_time{host_name=\"$host\"}) by (cpu))) - avg(sum by (mode)(rate(system_cpu_time{state='idle',host_name=\"$host\"}[$__rate_interval])))) * 100) / count(count(system_cpu_time{host_name=\"$host\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "$host memoryUsed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 8 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_memory_usage{state!=\"free\",host_name=\"$host\"})",
     "legendFormat": "{{host_name}}"
    },
    {}
   ]
  },
  {
   "title": "Disk Activity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(system_disk_io{host_name=\"$host\",direction=\"read\"}[$__rate_interval]))",
     "legendFormat": "Disk Read"
    },
    {
     "expr": "sum(rate(system_disk_io{host_name=\"$host\",direction=\"write\"}[$__rate_interval]))",
     "legendFormat": "Disk Write"
    }
   ]
  },
  {
   "title": "Network Activity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(system_network_io{host_name=\"$host\",direction=\"receive\"}[$__rate_interval]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(rate(system_network_io{host_name=\"$host\",direction=\"transmit\"}[$__rate_interval]))",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "File System Use",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_filesystem_usage{host_name=\"$host\",state=\"used\"}) by (mountpoint) / sum(system_filesystem_usage{host_name=\"$host\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    },
    {}
   ]
  }
 ]
}