scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'pi-hole'
    scrape_interval: 30s
    static_configs:
      - targets: ['homelab-monitoring_pi-hole-exporter_1:9617']
  - job_name: 'snmp'
    metrics_path: /snmp
    params:
      module: [if_mib]
    static_configs:
      - targets:
        - 192.168.2.1  # SNMP device - add your IPs here
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.2.113:9116  # SNMP exporter.
  - job_name: 'otel-collector'
    scrape_interval: 30s
    static_configs:
      - targets: ['homelab-monitoring_otel-collector_1:8888']
  - job_name: 'otel-windows'
    scrape_interval: 30s
    static_configs:
      - targets: ['192.168.2.161:9101', '192.168.2.212:9101', '192.168.2.41:9101']
  - job_name: 'minecraft'
    scrape_interval: 30s
    static_configs:
      - targets: [192.168.2.113:9225]
  - job_name: 'speedtest'
    scrape_interval: 30m
    scrape_timeout: 60s
    static_configs: 
      - targets: ['homelab-monitoring_speedtest_1:9091']